### ISSUE TITLE
Tendrl login screen tells the user that password is wrong when tendrl-api is down

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/ui#468]
When tendrl-api service is down, tendrl login screen doesn't notify the user about the problem and only displays general bad password message ,so that the issue can't be distinguished from wrong username/password combination.

This is bad because it confuses the user when the problem is obvious and could be reported outright.

## Version

tendrl-dashboard-1.4.2-1.el7.centos.noarch

## Reproducer

1. Install Tendrl Server using tendrl-ansible
2. Stop `tendrl-api` serivice on Tendr Server: `systemctl stop tendrl-api`
3. Enable firebug console (for watching http requests) and go to tendrl login page
4. Enter correct username/password combination
5. See the error message

## Actual Results

The Tendrl web just states that:

> The username or password you entered does not match our records. Please try again.

While in the console, the error is clearly visible:

> "NetworkError: 503 Service Unavailable

As can be seen here:

![todo-issue 005](https://user-images.githubusercontent.com/4759819/27499004-15a1150e-5862-11e7-80ff-14649161fc51.png)

## Expected Results

The actual root cause of the problem is reported: the tendrl-api can't be reached (NetworkError: 503 Service Unavailable)

**Comment by gnehapk** [comment]
@julienlim @mcarrano Can you please suggest the error message description when the API fails while logging.

**Comment by julienlim** [comment]
@gnehapk 

Here's what I would suggest: "Tendrl API is not reachable. Please <put suggested resolution here>."

As a best practice, when telling user something is wrong, it would be useful that it followed by how to fix it.

@rghatvis@redhat.com Please feel free to change / edit suggested error message to be shown.

**Comment by r0h4n** [comment]
@gnehapk Is this done?

**Comment by gnehapk** [comment]
@julienlim I think its an incomplete message. Can you please check it once.

**Comment by julienlim** [comment]
@gnehapk Not sure what happened to the text I put there, try this:

Tendrl API is not reachable. Please restart the Tendrl API server by <CLI command to restart Tendrl API server> before logging in."

Please check with @r0h4n what the command is to restart, or is there are multiple steps in order to resolve.

**Comment by gnehapk** [comment]
Done.

**Comment by dahorak** [comment]
Could you please reopen this issue, as it is still not fixed?
And once it will be fixed, could you please link here the related PR or Commit?

**Comment by gnehapk** [comment]
Closing this issue as it is fixed. Please reopen the issue if it is reproducible.
