### ISSUE TITLE
Inconsistent status icon for node down (disconnected)

### ISSUE THREAD

**Issue by julienlim** [Tendrl/ui#664]
Inconsistent status icon for node down (disconnected) - see node4

<img width="1122" alt="screen shot 2017-10-06 at 1 03 57 pm" src="https://user-images.githubusercontent.com/5589919/31289557-1c2c3a5c-aa97-11e7-997b-a28de8cd908b.png">

<img width="1124" alt="screen shot 2017-10-06 at 1 04 09 pm" src="https://user-images.githubusercontent.com/5589919/31289565-245c7336-aa97-11e7-8101-832673e4f7e3.png">

@gnehapk @a2batic @Tendrl/tendrl-qe @mcarrano

**Comment by cybernth** [comment]
@julienlim, I see an inconsistency between host and cluster list pages. So which is correct? The icon implemented in host list?

**Comment by mkudlej** [comment]
I see this issue too with
```
etcd-3.2.5-1.el7.x86_64
glusterfs-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-api-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-cli-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-geo-replication-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-libs-4.0dev-0.181.git938adde.el7.centos.x86_64
glusterfs-server-4.0dev-0.181.git938adde.el7.centos.x86_64
python2-gluster-4.0dev-0.181.git938adde.el7.centos.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-ansible-1.5.3-20171006T142729.a80b984.noarch
tendrl-api-1.5.2-20171006T095605.71ea692.noarch
tendrl-api-httpd-1.5.2-20171006T095605.71ea692.noarch
tendrl-commons-1.5.2-20171004T104238.6d5ffef.noarch
tendrl-grafana-plugins-1.5.2-20171009T072405.ed38272.noarch
tendrl-monitoring-integration-1.5.2-20171009T072405.ed38272.noarch
tendrl-node-agent-1.5.2-20171007T091926.0f2fd9b.noarch
tendrl-notifier-1.5.2-20171009T082044.7908e91.noarch
tendrl-ui-1.5.2-20171006T150811.7f212c5.noarch
```

**Comment by julienlim** [comment]
@nthomas-redhat @mkudlej @mcarrano @Tendrl/tendrl-qe @gnehapk @a2batic 

Cluster status icons can be found at: https://redhat.invisionapp.com/share/589XIRJBW#/screens/214068213

Host status icons can be found at https://redhat.invisionapp.com/share/589XIRJBW#/screens/214068213.

**Comment by a2batic** [comment]
@julienlim The Issue has been fixed, Please verify with the master build(tendrl-ui-1.5.2-20171011T095120.b554d56.noarch.rpm).

**Comment by julienlim** [comment]
@a2batic @gnehapk I just redeployed tendrl from master using tendrl-ansible, and it looks like the one on the cluster list page is still not updated.  See attached.  Right now, if you look at node4, the status icon is not there.

<img width="1182" alt="screen shot 2017-10-11 at 2 35 38 pm" src="https://user-images.githubusercontent.com/5589919/31459596-a1cf8d3c-ae91-11e7-9852-0b516b16e23b.png">

<img width="1184" alt="screen shot 2017-10-11 at 2 35 47 pm" src="https://user-images.githubusercontent.com/5589919/31459604-a43e0f4e-ae91-11e7-9b4c-3f70b0c5a53b.png">

**Comment by a2batic** [comment]
@julienlim, Its working for me
![screenshot from 2017-10-12 01-13-34](https://user-images.githubusercontent.com/12200504/31462853-8fe5b764-aebd-11e7-86ef-400696c7547a.png)

Can you please provide the API response of cluster list and host list once?

**Comment by julienlim** [comment]
@a2batic 

**API response for cluster list:**
$ curl -XGET -H "Authorization: Bearer 53627ab113ca571a56e40f061828950202e2b69169ed1c3ef8e3da29a8d93c06" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/clusters

{"clusters":[{"cluster_id":"1b35a38d-499a-4600-984f-f6caed7560c2","integration_id":"1b35a38d-499a-4600-984f-f6caed7560c2","hash":"becfedc3aaeb520d65e0667c12840312","sds_version":"3.12.1","updated_at":"2017-10-11 16:30:41.055240+00:00","sds_name":"gluster","cluster_name":"gluster-41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","errors":[],"globaldetails":{"connection_active":"0","volume_up_degraded":"0","peer_count":"4","updated_at":"2017-10-11 18:01:39.042590+00:00","vol_count":"1","hash":"d219e680955ae9e3382c2d0bf141dbb1","connection_count":"0","status":"unhealthy"},"public_network":"","cluster_network":"","is_managed":"yes","enable_volume_profiling":"yes","import_status":"done","import_job_id":"1de21e33-ad83-4b07-9d9b-b80671f58acc","nodes":[{"status":"UP","hash":"b30cb66e1529fc64b1941e45ac1245c6","tags":["tendrl/integration/gluster","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/node_a1bf6dcd-de5c-40b0-baf1-7027fa7273a5","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"sync_status":"done","fqdn":"node3","updated_at":"2017-10-11 20:03:24.094833+00:00","node_id":"a1bf6dcd-de5c-40b0-baf1-7027fa7273a5","last_sync":"2017-10-11 20:03:24.015409+00:00","node_id":"a1bf6dcd-de5c-40b0-baf1-7027fa7273a5"},{"last_sync":"2017-10-11 17:57:39.564675+00:00","hash":"f88b6b86188a27e98d39a5aa56323e1f","tags":["tendrl/integration/gluster","tendrl/node_d7e49479-376d-49b2-a984-058cca98c8bc","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"sync_status":"done","fqdn":"node4","updated_at":"2017-10-11 17:57:39.729713+00:00","node_id":"d7e49479-376d-49b2-a984-058cca98c8bc","node_id":"d7e49479-376d-49b2-a984-058cca98c8bc"},{"tags":["tendrl/integration/gluster","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/node_a6584574-5d22-4bbe-84a4-4d07c0fd4fa5","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"sync_status":"done","fqdn":"node1","updated_at":"2017-10-11 20:03:48.680342+00:00","node_id":"a6584574-5d22-4bbe-84a4-4d07c0fd4fa5","last_sync":"2017-10-11 20:03:48.602382+00:00","status":"UP","hash":"652130c46ebdab94e0080b9960102b87","node_id":"a6584574-5d22-4bbe-84a4-4d07c0fd4fa5"},{"last_sync":"2017-10-11 20:03:35.638694+00:00","status":"UP","hash":"04937d18f35f2bfb098f31ea1f38f69d","tags":["tendrl/integration/gluster","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/node_ea016aaf-cbce-45e1-9a31-478c609a0d23","provisioner/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"sync_status":"done","fqdn":"node2","updated_at":"2017-10-11 20:03:35.714747+00:00","node_id":"ea016aaf-cbce-45e1-9a31-478c609a0d23","node_id":"ea016aaf-cbce-45e1-9a31-478c609a0d23"}]}]}

**API response for host list:**

$ curl -XGET -H "Authorization: Bearer 53627ab113ca571a56e40f061828950202e2b69169ed1c3ef8e3da29a8d93c06" -H "Content-Type: application/json" http://127.0.0.1/api/1.0/nodes

{"nodes":[{"last_sync":"2017-10-11 20:06:53.436059+00:00","status":"UP","hash":"bfe9cca7f964174b8163236143c1cd4a","tags":["tendrl/integration/gluster","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/node_a6584574-5d22-4bbe-84a4-4d07c0fd4fa5","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"sync_status":"done","fqdn":"node1","updated_at":"2017-10-11 20:06:53.457570+00:00","node_id":"a6584574-5d22-4bbe-84a4-4d07c0fd4fa5","cluster":{"updated_at":"2017-10-11 16:27:23.281107+00:00","sds_name":"gluster","cluster_name":"gluster-41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","cluster_id":"41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","integration_id":"1b35a38d-499a-4600-984f-f6caed7560c2","hash":"79213dbbc1eea3cbd4720b3ec7c64ea7","sds_version":"3.12.1"}},{"sync_status":"done","fqdn":"node2","updated_at":"2017-10-11 20:06:40.638597+00:00","node_id":"ea016aaf-cbce-45e1-9a31-478c609a0d23","last_sync":"2017-10-11 20:06:40.611922+00:00","status":"UP","hash":"f14af233a1aef457151cb1ee9b1c5938","tags":["tendrl/integration/gluster","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/node_ea016aaf-cbce-45e1-9a31-478c609a0d23","provisioner/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"cluster":{"cluster_name":"gluster-41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","cluster_id":"41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","integration_id":"1b35a38d-499a-4600-984f-f6caed7560c2","hash":"79213dbbc1eea3cbd4720b3ec7c64ea7","sds_version":"3.12.1","updated_at":"2017-10-11 16:27:23.314305+00:00","sds_name":"gluster"}},{"sync_status":"done","fqdn":"node0","updated_at":"2017-10-11 20:06:29.904485+00:00","node_id":"90856f08-a5e5-4220-88e4-364a55692221","last_sync":"2017-10-11 20:06:29.871349+00:00","status":"UP","hash":"6ed0de40187d60154e656c6c01f909b2","tags":["tendrl/integration/monitoring","tendrl/central-store","tendrl/node_90856f08-a5e5-4220-88e4-364a55692221","tendrl/server","tendrl/monitor","tendrl/node"],"cluster":{"cluster_id":"","integration_id":"","hash":"f8952d244ec9d84e80f4bb993e409d85","sds_version":"","updated_at":"2017-10-11 16:25:13.592454+00:00","sds_name":"","cluster_name":""}},{"last_sync":"2017-10-11 20:06:30.170401+00:00","status":"UP","hash":"451bdcf48ce5298b1a418f020203cf38","tags":["tendrl/integration/gluster","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/node_a1bf6dcd-de5c-40b0-baf1-7027fa7273a5","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"sync_status":"done","fqdn":"node3","updated_at":"2017-10-11 20:06:30.191745+00:00","node_id":"a1bf6dcd-de5c-40b0-baf1-7027fa7273a5","cluster":{"cluster_id":"41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","integration_id":"1b35a38d-499a-4600-984f-f6caed7560c2","hash":"79213dbbc1eea3cbd4720b3ec7c64ea7","sds_version":"3.12.1","updated_at":"2017-10-11 16:27:23.116474+00:00","sds_name":"gluster","cluster_name":"gluster-41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf"}},{"status":"DOWN","hash":"f88b6b86188a27e98d39a5aa56323e1f","tags":["tendrl/integration/gluster","tendrl/node_d7e49479-376d-49b2-a984-058cca98c8bc","detected_cluster/41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","gluster/server","tendrl/integration/1b35a38d-499a-4600-984f-f6caed7560c2","tendrl/node"],"sync_status":"done","fqdn":"node4","updated_at":"2017-10-11 17:57:39.612682+00:00","node_id":"d7e49479-376d-49b2-a984-058cca98c8bc","last_sync":"2017-10-11 17:57:39.564675+00:00","cluster":{"sds_name":"gluster","cluster_name":"gluster-41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","cluster_id":"41370885bd2419249e23a0ebbb368a23210e88c364c6fbf7233bf87d4e459ecf","integration_id":"1b35a38d-499a-4600-984f-f6caed7560c2","hash":"79213dbbc1eea3cbd4720b3ec7c64ea7","sds_version":"3.12.1","updated_at":"2017-10-11 16:27:23.253862+00:00"}}]}

**Comment by gnehapk** [comment]
@anivargi `status` attribute is missing in the API response for node4.

**Comment by a2batic** [comment]
@julienlim, Fixed with tendrl-ui-1.5.3-20171012T142223.125d75e.noarch.rpm (latest master build). Please verify.

**Comment by julienlim** [comment]
@a2batic @gnehapk @Tendrl/tendrl-qe @mcarrano 

Have verified the fix that shows node4 is down with correct status icon.

<img width="1280" alt="screen shot 2017-10-18 at 2 40 20 pm" src="https://user-images.githubusercontent.com/5589919/31736516-0256fc5e-b413-11e7-93ab-64e999e29ccd.png">
